// autogenerated by typings-for-css-modules-loader.
declare namespace StyleScssNamespace {
  export interface IStyleScss {
    background: string;
    colorAccent: string;
    colorBackground: string;
    colorBase: string;
    colorDark: string;
    colorLight: string;
  }
}

declare const StyleScssModule: StyleScssNamespace.IStyleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StyleScssNamespace.IStyleScss;
};

export = StyleScssModule;
