const path = require('path');
// Load the plugin in your webpack.config.js file.
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ErrorOverlayPlugin = require('error-overlay-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const modules = ['app'];
const multipleHtmlPlugins = modules.map((name) => new HtmlWebpackPlugin({
    inject: true,
    template: `./${name}/public/index.html`, // relative path to the HTML files
    filename: `${name}/index.html`, // output HTML files
    chunks: [`${name}`], // respective JS files
}));

module.exports = {
    mode: 'development',
    entry: {
        app: './app/index.tsx',
    },
    output: {
        path: `${__dirname}/dist`,
        filename: '[name]/[name].js',
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx|ts|tsx)$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                },
            },
            // Add HTML loader to serve HTML files.
            {
                test: /\.html$/,
                use: [
                    {
                        loader: 'html-loader',
                    },
                ],
            },
            {
                test: /\.css$/i,
                use: [
                    'style-loader',
                    'css-loader',
                ],
            },
            {
                test: /\.s[ac]ss$/i,
                use: [
                    'style-loader',
                    {
                        loader: '@teamsupercell/typings-for-css-modules-loader',
                        options: {
                            banner: '// autogenerated by typings-for-css-modules-loader.',
                        },
                    },
                    // Translates CSS into CommonJS with modules
                    {
                        loader: 'css-loader',
                        options: {
                            modules: {
                                compileType: 'module',
                                exportGlobals: true,
                                exportLocalsConvention: 'camelCaseOnly',
                            },
                        },
                    },
                    // Compiles Sass to CSS
                    'sass-loader',
                ],
            },
            {
                test: /\.(jpg|jpeg|png|woff|woff2|eot|ttf|svg)$/,
                loader: 'url-loader',
                options: {
                    limit: 100000,
                },
            },
        ],
    },
    resolve: {
        modules: ['node_modules', 'app'],
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.json', 'css', 'scss'],
    },
    devServer: {
        contentBase: `${__dirname}/dist/app`,
        writeToDisk: true,
        compress: true,
        port: 9000,
        overlay: false,
        hot: true,
        transportMode: 'ws',
        injectClient: true,
    },
    devtool: 'cheap-module-source-map',
    // Call the Plugin here.
    plugins: [
        new ErrorOverlayPlugin(),
        new CleanWebpackPlugin({ cleanAfterEveryBuildPatterns: true }),
        new MiniCssExtractPlugin(),
        new webpack.DefinePlugin({
            'process.env': '{}',
            global: {},
        }),
    ].concat(multipleHtmlPlugins),
};
